AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Leaderboard application

Globals:
  Function:
    Timeout: 10
    MemorySize: 256
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'content-type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - image/x-icon
        - image/png
        - image/jpeg
        - audio/mpeg
        - application/octet-stream
        - application/json
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'content-type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: ./src
      Handler: lambda_handler.lambda_app
      Runtime: python3.12
      Events:
        RootPath:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: ANY
        ProxyPath:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          LEADERBOARD_TABLE: !Ref LeaderboardTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaderboardTable

  LeaderboardTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Leaderboard    # only needs to be unique within the account
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
        - AttributeName: Key
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH
        - AttributeName: Key
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
